source 'http://rubygems.org'

gem 'cucumber', '~> 3.1', '>= 3.1.2'
gem 'capybara'
gem 'rspec'
gem 'rake'
gem 'page-object'
gem 'pry'
gem 'site_prism'
gem 'rest-client'
gem 'savon'
gem 'webdrivers'
gem 'selenium-webdriver'
gem 'ffi'
